<?php
/**
 * Created by PhpStorm.
 * User: cronfy
 * Date: 09.06.16
 * Time: 10:54
 */

namespace cronfy\ylc\yii\web;

/**
 * Class View
 * @package lik\ylc\yii\web
 *
 * Extension of yii\web\view - helper functions for YLC
 */

class View extends \yii\web\View {

    /**
     * Extracts assets information from page generated by Yii.
     * @return array Html code for assets, required by generated page,
     * for View::POS_HEAD, View::POS_BEGIN end View::POS_END positions.
     */
    public function getPageAssets() {
        // code taken from View->endBody(), but without actually echoing html
        foreach (array_keys($this->assetBundles) as $bundle) {
            $this->registerAssetFiles($bundle);
        }

        return [
            'head' => $this->renderHeadHtml(),
            'body' => $this->renderBodyBeginHtml(),
            'end' => $this->renderBodyEndHtml(false /* ajaxMode */)
        ];

    }

}
